name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm config set registry https://registry.npmjs.org
      - run: npm install -g npm@latest
      - run: npm login --scope=@malba231180 --registry=https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
      - run: npm publish
      - run: npm logout --scope=@malba231180
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
